{
 "title": "Default",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 } },
  {
   "title": "Registration init requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "fivegs_amffunction_rm_reginitreq",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Registration failure",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "fivegs_amffunction_rm_reginitfail",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AMF Sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "amf_session", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SMF Sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fivegs_smffunction_sm_sessionnbr",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Registration success",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "fivegs_amffunction_rm_reginitsucc",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NF Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of gNBs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gnb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of UEs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ran_ue", "legendFormat": "__auto" }
   ]
  }
 ]
}