mcc: '001'
mnc: '01'

nci: '0x000000010'
idLength: 32
tac: 1

linkIp: 0.0.0.0
ngapIp: 0.0.0.0
gtpIp: 0.0.0.0

# AMF address as seen from the RAN network
amfConfigs:
  - address: 10.200.0.200
    port: 38412

# Supported S-NSSAIs
slices:
  - sst: 1

# If false, gNB will not send GTP-U packets
ignoreStreamIds: true
