logger:
  file:
    path: /open5gs/install/var/log/open5gs/sepp.log
    timestamp: true
  default:
    timestamp: false

global:
  max:
    ue: 1024

sepp:
  default:
    tls:
      server:
        private_key: /open5gs/install/etc/open5gs/tls/sepp1.key
        cert: /open5gs/install/etc/open5gs/tls/sepp1.crt
      client:
        cacert: /open5gs/install/etc/open5gs/tls/ca.crt
  sbi:
    server:
      - address: fiveg-cn-sepp
        port: 7777
    client:
      scp:
        - uri: http://fiveg-cn-scp:7777
