logger:
  file:
    path: /open5gs/install/var/log/open5gs/udm.log
    timestamp: true
  default:
    timestamp: false

global:
  max:
    ue: 1024

udm:
  sbi:
    server:
      - address: fiveg-cn-udm
        port: 7777
    client:
      nrf:
        - uri: http://fiveg-cn-nrf:7777
      scp:
        - uri: http://fiveg-cn-scp:7777
